name: Playwright Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:
    inputs:
      test_suite:
        description: 'Выберите набор тестов для запуска'
        type: choice
        options:
          - all
          - get
          - put
          - patch
          - post
          - delete

        default: all

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run all tests
        if: ${{ github.event.inputs.test_suite == 'all' }}
        run: npx playwright test

      - name: Run get tests
        if: ${{ github.event.inputs.test_suite == 'get' }}
        run: npx playwright test --grep @get

      - name: Run put tests
        if: ${{ github.event.inputs.test_suite == 'put' }}
        run: npx playwright test --grep @put
      
      - name: Run post tests
        if: ${{ github.event.inputs.test_suite == 'post' }}
        run: npx playwright test --grep @post

      - name: Run patch tests
        if: ${{ github.event.inputs.test_suite == 'patch' }}
        run: npx playwright test --grep @patch

      - name: Run delete tests
        if: ${{ github.event.inputs.test_suite == 'delete' }}
        run: npx playwright test --grep @delete

      - name: Upload Playwright report
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30